version: '3.9'

networks:
  dotgame:
    driver: bridge

services:
  database:
    container_name: dotgame-database
    image: postgres
    environment:
      POSTGRES_DB: "dotgame"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - dotgame
  main:
    container_name: dotgame-nest
    image: node:17.5.0-alpine
    depends_on:
      - database
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - dotgame
